fixup P2P_PORT and add bootstrap node port support to the base stateful set startup script

diff --git a/chains/caimst-209301/base/node/statefulset.yaml b/chains/caimst-209301/base/node/statefulset.yaml
--- a/chains/caimst-209301/base/node/statefulset.yaml
+++ b/chains/caimst-209301/base/node/statefulset.yaml
@@ -127,34 +127,77 @@ spec:
           - |
             set -ex
 
-            NAT_OPTS="--nat=none"
-
-            # quorum resolves the bootnode dns names once on startup
-            if [ -n "$BOOTNODE_PUB0" ]; then
-              BOOTNODES=enode://${BOOTNODE_PUB0}@${BOOTNODE_HOST0}:${P2P_PORT}
-            fi
-
-            if [ -n "$BOOTNODE_PUB1" ]; then
-              [ -n "${BOOTNODES}" ] && BOOTNODES="${BOOTNODES},"
-              BOOTNODES="${BOOTNODES}enode://${BOOTNODE_PUB1}@${BOOTNODE_HOST1}:${P2P_PORT}"
-            fi
-
-            # if we expect bootnodes and are not one of them, hang around until
-            # one is available. k8s dns will fail until the node is ready
-            HOSTNAME=$(hostname -f)
-            if [ -n "$BOOTNODE_PUB0" ] && { [ "${HOSTNAME}" != "${BOOTNODE_HOST0}" ] && [ "${HOSTNAME}" != "${BOOTNODE_HOST1}" ]; }; then
-            while true; do
-              [ -n "${BOOTNODE_HOST0}" ] && nslookup -type=a ${BOOTNODE_HOST0} && break
-              [ -n "${BOOTNODE_HOST1}" ] && nslookup -type=a ${BOOTNODE_HOST1} && break
-              echo "waiting for a bootnode to be available ..."
+            # touch SLEEPING
+            while [ -f SLEEPING ]; do
               sleep 1
+              echo "sleeping for 1s"
             done
+            apt-get install -y netcat
+
+            if [ -n "${EXTIP}" ]; then
+              # if we want to permit external peers we should set the external
+              # ip. Othwerwise set the lan ip as that lets the bootnodes connect to each other.
+              # For bootnodes on extip:PUBLIC-IP the reported IP is WAN but the resolved is local and geth disallows this
+              # with the consequence that the bootnodes don't connect to each
+              # other
+              export NAT_OPTS="--nat=extip:${EXTIP}"
+              #export NAT_OPTS="--nat=extip:${POD_IP}"
+              #export NAT_OPTS="--nat=none"
+            else
+              export NAT_OPTS="--nat=extip:${POD_IP}"
             fi
-            if [ -n "$BOOTNODE_PUB0" ]; then
-              if  { [ "${HOSTNAME}" = "${BOOTNODE_HOST0}" ] || [ "${HOSTNAME}" = "${BOOTNODE_HOST1}" ]; }; then
-                DISCOVERY_OPTS="--netrestrict=${POD_IP}/16"
-              else
-                DISCOVERY_OPTS="--netrestrict=${POD_IP}/16 --bootnodes=${BOOTNODES}"
+
+            if [ -n "$BOOTNODE0_NODEPORT" ]; then
+                [ -z "${BOOTNODE0_EXTIP}" ] && echo "BOOTNODE0_NODEPORT requires BOOTNODE0_EXTIP" && exit 1
+                [ -z "${BOOTNODE1_EXTIP}" ] && echo "Using the NODEPORT feature requires two bootnodes" && exit 1
+
+                export BOOTNODES=enode://${BOOTNODE_PUB0}@${BOOTNODE0_EXTIP}:${BOOTNODE0_NODEPORT}
+                if [ -n "$BOOTNODE1_NODEPORT" ]; then
+                  [ -z "${BOOTNODE1_EXTIP}" ] && echo "BOOTNODE1_NODEPORT requires BOOTNODE1_EXTIP" && exit 1
+                  [ -n "${BOOTNODES}" ] && BOOTNODES="${BOOTNODES},"
+                  export BOOTNODES=${BOOTNODES}enode://${BOOTNODE_PUB1}@${BOOTNODE1_EXTIP}:${BOOTNODE1_NODEPORT}
+                fi
+
+                HOSTNAME=$(hostname -f)
+                if [ -n "${EXTIP}" ]; then
+                while true; do
+                  [ -n "${BOOTNODE0_EXTIP}" ] && nc -vzu ${BOOTNODE0_EXTIP} ${BOOTNODE0_NODEPORT} && break
+                  [ -n "${BOOTNODE1_EXTIP}" ] && nc -vzu ${BOOTNODE1_EXTIP} ${BOOTNODE1_NODEPORT} && break
+                  echo "waiting for a bootnode to be available ..."
+                  sleep 1
+                done
+                fi
+
+                DISCOVERY_OPTS="--netrestrict=${BOOTNODE0_EXTIP}/32,${BOOTNODE1_EXTIP}/32,${POD_IP}/16 --bootnodes=${BOOTNODES}"
+                DISCOVERY_OPTS="--bootnodes=${BOOTNODES}"
+            else
+              # quorum resolves the bootnode dns names once on startup
+              if [ -n "$BOOTNODE_PUB0" ]; then
+                BOOTNODES=enode://${BOOTNODE_PUB0}@${BOOTNODE_HOST0}:${P2P_PORT}
+              fi
+
+              if [ -n "$BOOTNODE_PUB1" ]; then
+                [ -n "${BOOTNODES}" ] && BOOTNODES="${BOOTNODES},"
+                BOOTNODES="${BOOTNODES}enode://${BOOTNODE_PUB1}@${BOOTNODE_HOST1}:${P2P_PORT}"
+              fi
+
+              # if we expect bootnodes and are not one of them, hang around until
+              # one is available. k8s dns will fail until the node is ready
+              HOSTNAME=$(hostname -f)
+              if [ -n "$BOOTNODE_PUB0" ] && { [ "${HOSTNAME}" != "${BOOTNODE_HOST0}" ] && [ "${HOSTNAME}" != "${BOOTNODE_HOST1}" ]; }; then
+              while true; do
+                [ -n "${BOOTNODE_HOST0}" ] && nslookup -type=a ${BOOTNODE_HOST0} && break
+                [ -n "${BOOTNODE_HOST1}" ] && nslookup -type=a ${BOOTNODE_HOST1} && break
+                echo "waiting for a bootnode to be available ..."
+                sleep 1
+              done
+              fi
+              if [ -n "$BOOTNODE_PUB0" ]; then
+                if  { [ "${HOSTNAME}" = "${BOOTNODE_HOST0}" ] || [ "${HOSTNAME}" = "${BOOTNODE_HOST1}" ]; }; then
+                  DISCOVERY_OPTS="--netrestrict=${POD_IP}/16"
+                else
+                  DISCOVERY_OPTS="--netrestrict=${POD_IP}/16 --bootnodes=${BOOTNODES}"
+                fi
               fi
             fi
 
@@ -164,6 +207,8 @@ spec:
             [ -f /config/static-nodes.json ] && cp -v /config/static-nodes.json /data/node/ && cat /data/node/static-nodes.json
 
             cd /data/node
+            env | grep _OPTS
+            env | grep BOOTNODE
             PRIVATE_CONFIG=ignore geth \
                 --identity ${APP_LABEL} \
                 --networkid ${NETWORKID} \
@@ -198,6 +243,7 @@ spec:
             set -e
             [ -f /data/node/geth/LOCK ] && exit 0
             echo "initialising node"
+            apt-get install -y jq netcat
             geth init \
                 --datadir /data/node \
                   /config/genesis.json
